travis:
  secure:
    BINSTAR_TOKEN: uZeZQKGQnFDKWPIimiFNyGES/7jDi0+cfmrZOzFoXMGv/1ldWaQwziMnSo6ib0FuzCMllffdZwR6OG//VN6mb3XqgeSvoA6AbNgdFBbDQ1XMPDecm3Rxu4WLt4Q4+RfNgpRWGsCEWPxZ4cP84NYeBn+uhcqRsqOv6/54kWkIysEV8CnwXrx5J8yGEup2r/jcHMOBr/NwjTozPpSRR31VttNXW0uDMVdCwwkoO8kbbTx5Op60i7f+TfWGbT1FoySseSDzdu59Nl4IA+4gyfWaklHZxClSRdmwNYjpRerbOBWQMpa3cbN8Xc8U010bm8wmyKU4l7f4QbYnqQ5gp47GRpI5WL4BKYtvoDMAD80RCdB1VZn0EQA4w4qN+7PLTqt4VR7O0lA0zBrGFiA0R/luGPWVz2pI8PtnSHX+4h5V3Z2P7/UiwNe9pJCKy9BEWa4/dXbu+mZBm95PFcGwEMldIet6oqnQ6cACFt/mDM4/aDMKU4t87E2yxk8y0WHRcDLTCYJiVTuy4j+xGqmd3KATmmGhivWXTk7mD8pK5getmGvqwjRBCvB7QcKTJifnLD/alrYG/xgEfopKoUGJ7g/RNCYjyRA4nB6uRY/C1ye1bZlGgT4YmfrERXGMxGseQuLLL24VpX7Mz2kEq3au22ZXGmu78cZbDlQso24BIvlxHS4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
